"""
Figure File Mover Utility

This module provides functionality to move figure files generated by engcom.show() 
from the project root to the proper hierarchical directory structure under /media/notebooks/.

The engcom.show() function saves figures to the current working directory, but the 
pandoc filter expects them in the *_files directory structure. This utility bridges
that gap by automatically moving files after notebook execution.
"""

import os
import shutil
from pathlib import Path
from typing import List, Dict


def identify_figure_files(directory: Path = None) -> List[Path]:
    """
    Identify figure files that were generated by engcom.show() in the given directory.
    
    Args:
        directory: Directory to search for figure files. Defaults to current working directory.
        
    Returns:
        List of Path objects for identified figure files.
    """
    if directory is None:
        directory = Path.cwd()
    else:
        directory = Path(directory)

    # Common patterns for engcom-generated figure files
    patterns = [
        'figure-*.svg',
        'figure-*.png',
        'figure-*.pdf',
        'figure-*.pgf',
        'figure-*.eps',
        'autofig-*.svg',
        'autofig-*.png',
        'autofig-*.gif',
        'figure-*-img*.png',  # For subfigures/composite figures
        'figure-*-img*.svg',
        '*-figure-*.svg',     # Files with prefix like "simulation-figure-1.svg"
        '*-figure-*.png',
        '*-figure-*.pdf',
        '*-figure-*.pgf',
        '*-figure-*.eps',
        'output_*_*.png',     # Jupyter notebook cell output pattern
        'output_*_*.svg',
        'output_*_*.gif',
    ]

    figure_files = []

    for pattern in patterns:
        matches = directory.glob(pattern)
        figure_files.extend(matches)

    # Also check for any files that match matplotlib's default naming
    # when using savefig without explicit filename
    additional_patterns = [
        'Unnamed*.png',
        'Unnamed*.svg',
        'temp_figure*.png',
        'temp_figure*.svg',
        'temp_figure*.gif',
    ]

    for pattern in additional_patterns:
        matches = directory.glob(pattern)
        figure_files.extend(matches)

    # Remove duplicates and return sorted list
    unique_files = list(set(figure_files))
    return sorted(unique_files)


def determine_destination_path(source_notebook_path: Path) -> Path:
    """
    Determine the correct destination path for figure files based on the source notebook path.
    
    Args:
        source_notebook_path: Path to the source .py file in notebooks-source
        
    Returns:
        Path to the destination *_files directory where figures should be moved.
        
    Examples:
        teaching/notebooks-source/sample-notebook/chapter_intro/intro_code.py
        -> media/notebooks/sample-notebook/chapter_intro/intro_code_files/
        
        teaching/notebooks-source/heat-transfer/chapter_conduction/examples.py  
        -> media/notebooks/heat-transfer/chapter_conduction/examples_files/
    """
    source_path = Path(source_notebook_path)

    # Extract components from the source path
    # Expected format: teaching/notebooks-source/{notebook_name}/{chapter_name}/{file_name}.py
    parts = source_path.parts

    try:
        # Find the notebooks-source part
        source_index = parts.index('notebooks-source')

        if len(parts) > source_index + 3:  # notebooks-source + notebook + chapter + file
            notebook_name = parts[source_index + 1]
            chapter_name = parts[source_index + 2]
            file_stem = source_path.stem  # filename without extension

            # Construct destination path
            destination = Path('media') / 'notebooks' / notebook_name / chapter_name / f'{file_stem}_files'
            return destination
        else:
            # Fallback: simpler structure
            notebook_name = parts[source_index + 1]
            file_stem = source_path.stem
            destination = Path('media') / 'notebooks' / notebook_name / f'{file_stem}_files'
            return destination

    except (ValueError, IndexError):
        file_stem = source_path.stem

        # Parody content-repo layout: <project>/chapters/<chapter>/<file>.py
        # with the notebook slug supplied by the build via env var.
        if 'chapters' in parts:
            chapters_index = parts.index('chapters')
            notebook_name = os.environ.get('PARODY_NOTEBOOK_SLUG', 'unknown')
            if len(parts) > chapters_index + 2:
                chapter_name = parts[chapters_index + 1]
                return Path('media') / 'notebooks' / notebook_name / chapter_name / f'{file_stem}_files'
            return Path('media') / 'notebooks' / notebook_name / f'{file_stem}_files'

        # Legacy layout (chapter_*/ dirs) outside a notebooks-source/ tree,
        # i.e. a standalone content repo keeping the homepage structure:
        # slug from the env var, chapter from the chapter_* path component.
        notebook_name = os.environ.get('PARODY_NOTEBOOK_SLUG')
        if notebook_name:
            chapter_name = next(
                (p for p in parts if p.startswith('chapter_')), None)
            if chapter_name:
                return Path('media') / 'notebooks' / notebook_name / chapter_name / f'{file_stem}_files'
            return Path('media') / 'notebooks' / notebook_name / f'{file_stem}_files'

        # If we can't parse the path, create a fallback destination
        destination = Path('media') / 'notebooks' / 'unknown' / f'{file_stem}_files'
        return destination


def move_figures_to_media(source_notebook_path: Path, figure_files: List[Path],
                         media_root: Path = None, dry_run: bool = False) -> Dict[str, any]:
    """
    Move figure files to the appropriate media directory structure.
    
    Args:
        source_notebook_path: Path to the source .py notebook file
        figure_files: List of figure file paths to move
        media_root: Root directory for media files. Defaults to 'media' in current directory.
        dry_run: If True, only show what would be moved without actually moving files
        
    Returns:
        Dictionary containing results of the move operation
    """
    if media_root is None:
        media_root = Path.cwd()

    # Determine destination directory
    relative_dest_path = determine_destination_path(source_notebook_path)
    absolute_dest_path = media_root / relative_dest_path

    results = {
        'source_notebook': str(source_notebook_path),
        'destination_dir': str(absolute_dest_path),
        'moved_files': [],
        'failed_files': [],
        'errors': [],
        'dry_run': dry_run
    }

    if not figure_files:
        results['message'] = "No figure files found to move"
        return results

    # Create destination directory if it doesn't exist (unless dry run)
    if not dry_run:
        try:
            absolute_dest_path.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            results['errors'].append(f"Failed to create destination directory: {e}")
            return results

    # Move each figure file
    for figure_file in figure_files:
        try:
            dest_file_path = absolute_dest_path / figure_file.name

            if dry_run:
                results['moved_files'].append({
                    'source': str(figure_file),
                    'destination': str(dest_file_path),
                    'action': 'would_move'
                })
            else:
                # Check if destination file already exists
                if dest_file_path.exists():
                    # Create backup or overwrite based on policy
                    backup_path = dest_file_path.with_suffix(f'{dest_file_path.suffix}.backup')
                    shutil.move(str(dest_file_path), str(backup_path))

                # Move the file
                shutil.move(str(figure_file), str(dest_file_path))

                results['moved_files'].append({
                    'source': str(figure_file),
                    'destination': str(dest_file_path),
                    'action': 'moved'
                })

        except Exception as e:
            results['failed_files'].append(str(figure_file))
            results['errors'].append(f"Failed to move {figure_file}: {e}")

    return results


def cleanup_moved_figures(source_directory: Path = None,
                         backup_pattern: str = "*.backup") -> int:
    """
    Clean up any backup files created during figure moves.
    
    Args:
        source_directory: Directory to clean up. Defaults to current working directory.
        backup_pattern: Glob pattern for backup files to remove
        
    Returns:
        Number of backup files removed
    """
    if source_directory is None:
        source_directory = Path.cwd()

    backup_files = source_directory.glob(backup_pattern)
    count = 0

    for backup_file in backup_files:
        try:
            backup_file.unlink()
            count += 1
        except Exception:
            pass  # Ignore errors when cleaning up

    return count


def move_figures_after_notebook_execution(source_notebook_path: Path,
                                        working_directory: Path = None,
                                        verbose: bool = True) -> Dict[str, any]:
    """
    Main function to identify and move figures after notebook execution.
    
    This is the primary function to call after executing a notebook to move
    any generated figure files to the proper media directory structure.
    
    Args:
        source_notebook_path: Path to the source .py notebook file that was executed
        working_directory: Directory where figures were saved. Defaults to current directory.
        verbose: Whether to print status messages
        
    Returns:
        Dictionary containing results of the operation
    """
    if working_directory is None:
        working_directory = Path.cwd()

    # Find figure files in the working directory
    figure_files = identify_figure_files(working_directory)

    if verbose and figure_files:
        print(f"Found {len(figure_files)} figure files to move:")
        for fig_file in figure_files:
            print(f"  - {fig_file.name}")

    # Move the figures
    results = move_figures_to_media(
        source_notebook_path=source_notebook_path,
        figure_files=figure_files,
        media_root=working_directory,  # Assumes media/ is relative to working directory
        dry_run=False
    )

    if verbose:
        if results['moved_files']:
            print(f"✓ Moved {len(results['moved_files'])} figure files to: {results['destination_dir']}")
        if results['failed_files']:
            print(f"⚠ Failed to move {len(results['failed_files'])} files")
        if results['errors']:
            for error in results['errors']:
                print(f"❌ {error}")

    return results


def get_figure_file_mapping(source_notebook_path: Path,
                           working_directory: Path = None) -> Dict[str, str]:
    """
    Get a mapping of figure files to their destination paths without moving them.
    
    This is useful for understanding where files will be moved or for updating
    references in markdown files.
    
    Args:
        source_notebook_path: Path to the source .py notebook file
        working_directory: Directory where figures are located
        
    Returns:
        Dictionary mapping source paths to destination paths
    """
    if working_directory is None:
        working_directory = Path.cwd()

    figure_files = identify_figure_files(working_directory)
    relative_dest_path = determine_destination_path(source_notebook_path)
    absolute_dest_path = working_directory / relative_dest_path

    mapping = {}
    for figure_file in figure_files:
        dest_file_path = absolute_dest_path / figure_file.name
        mapping[str(figure_file)] = str(dest_file_path)

    return mapping


# CLI functionality for testing and manual use
def main():
    """Command line interface for testing the figure mover."""
    import argparse

    parser = argparse.ArgumentParser(description='Move engcom figure files to proper media structure')
    parser.add_argument('notebook_path', help='Path to the source notebook .py file')
    parser.add_argument('--working-dir', default='.', help='Directory where figures are located')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be moved without moving')
    parser.add_argument('--quiet', action='store_true', help='Suppress verbose output')

    args = parser.parse_args()

    source_path = Path(args.notebook_path)
    working_dir = Path(args.working_dir)

    if args.dry_run:
        figure_files = identify_figure_files(working_dir)
        results = move_figures_to_media(source_path, figure_files, working_dir, dry_run=True)

        print(f"Dry run results for {source_path}:")
        print(f"Destination: {results['destination_dir']}")
        print(f"Files that would be moved: {len(results['moved_files'])}")
        for file_info in results['moved_files']:
            print(f"  {file_info['source']} -> {file_info['destination']}")
    else:
        results = move_figures_after_notebook_execution(
            source_path, working_dir, verbose=not args.quiet
        )

        if results['errors']:
            exit(1)


if __name__ == '__main__':
    main()
